data = {
    showprice: true,
    booking_date: "22-4-2022",
    contact_number: "999999999",
    airline_pnr: "hkknd236",
    project_code: "",
    billing_name: "2D ENTERTAINMENT",
    issue_id: "AIR ARABIA",
    sale_amount: "2000",
    purchased_amount: "1500",
    approved_by: "",
    issued_by: "SURESH C",
    itenary: [
        {
            from: "Chennai(MAA)",
            from_terminal: "3",
            to_terminal: "2",
            to: "Mumbai(BOM)",
            travel_date: "25-4-2022",
            flight: "Indigo 6E-",
            departure: "6:00",
            arrival: "9:00",
            status: "Confirmed",
        },
        {
            from: "Chennai(MAA)",
            from_terminal: "3",
            to_terminal: "2",
            to: "Mumbai(BOM)",
            travel_date: "25-4-2022",
            flight: "Indigo 6E-",
            departure: "6:00",
            arrival: "9:00",
            status: "Confirmed",
        },            
    ],
    passengers: [
        {
            mrs: "Mr",
            name: "test name",
            age: "Adult",
            ticket_number: "243216845",
            frequent_flyer: "yes",
            booking_class: "Economy",
            fare_type: "Corporate",
            meal: "0",
            seat: "2B",
            baggage: "",

        },
        {
            mrs: "Mr",
            name: "test name",
            age: "Adult",
            ticket_number: "24326845",
            frequent_flyer: "yes",
            booking_class: "Economy",
            fare_type: "Corporate",
            meal: "0",
            seat: "2B",
            baggage: "",

        },
    ],
    itenary_type: "dom",
    req_fare_type: "basic",
    gds_name: "Amadeus",
    plb: "1",
    cbi: "15",
    air_fare: "200",
    additional_sc: "10",
    airportlo: "1788",
    igst: "",
    cgst: "1",
    sgst: "1",
    total: "2000",
  }